/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlunoTGN
 */
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Botao9 = new javax.swing.JButton();
        Botao7 = new javax.swing.JButton();
        Botao8 = new javax.swing.JButton();
        Botao4 = new javax.swing.JButton();
        Botao5 = new javax.swing.JButton();
        Botao6 = new javax.swing.JButton();
        Botao1 = new javax.swing.JButton();
        Botao2 = new javax.swing.JButton();
        Botao3 = new javax.swing.JButton();
        BotaoBackspace = new javax.swing.JButton();
        BotaoIgual = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoAdicao = new javax.swing.JButton();
        BotaoSubtracao = new javax.swing.JButton();
        Botao0 = new javax.swing.JButton();
        BotaoMultiplicacao = new javax.swing.JButton();
        BotaoDivisao = new javax.swing.JButton();
        BotaoVirgula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setToolTipText("digite o número");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        Botao9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao9.setText("9");
        Botao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao9MouseClicked(evt);
            }
        });

        Botao7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao7.setText("7");
        Botao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao7MouseClicked(evt);
            }
        });

        Botao8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao8.setText("8");
        Botao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao8MouseClicked(evt);
            }
        });

        Botao4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao4.setText("4");
        Botao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao4MouseClicked(evt);
            }
        });

        Botao5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao5.setText("5");
        Botao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao5MouseClicked(evt);
            }
        });

        Botao6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao6.setText("6");
        Botao6.setToolTipText("");
        Botao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao6MouseClicked(evt);
            }
        });

        Botao1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao1.setText("1");
        Botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao1MouseClicked(evt);
            }
        });
        Botao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Botao1KeyPressed(evt);
            }
        });

        Botao2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao2.setText("2");
        Botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao2MouseClicked(evt);
            }
        });

        Botao3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao3.setText("3");
        Botao3.setToolTipText("");
        Botao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao3MouseClicked(evt);
            }
        });

        BotaoBackspace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoBackspace.setText("<-");
        BotaoBackspace.setToolTipText("");
        BotaoBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoBackspaceMouseClicked(evt);
            }
        });

        BotaoIgual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoIgual.setText("=");
        BotaoIgual.setToolTipText("");
        BotaoIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoIgualMouseClicked(evt);
            }
        });
        BotaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIgualActionPerformed(evt);
            }
        });

        BotaoLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoLimpar.setText("C");
        BotaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoLimparMouseClicked(evt);
            }
        });

        BotaoAdicao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoAdicao.setText("+");
        BotaoAdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoAdicaoMouseClicked(evt);
            }
        });

        BotaoSubtracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSubtracao.setText("-");
        BotaoSubtracao.setToolTipText("");
        BotaoSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSubtracaoMouseClicked(evt);
            }
        });

        Botao0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao0.setText("0");
        Botao0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao0MouseClicked(evt);
            }
        });

        BotaoMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoMultiplicacao.setText("X");
        BotaoMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoMultiplicacaoMouseClicked(evt);
            }
        });

        BotaoDivisao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoDivisao.setText("/");
        BotaoDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoDivisaoMouseClicked(evt);
            }
        });

        BotaoVirgula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoVirgula.setText(",");
        BotaoVirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoVirgulaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BotaoBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao7MouseClicked
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_Botao7MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Botao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao8MouseClicked
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_Botao8MouseClicked

    private void Botao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao9MouseClicked
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_Botao9MouseClicked

    private void Botao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao4MouseClicked
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_Botao4MouseClicked

    private void Botao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao5MouseClicked
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_Botao5MouseClicked

    private void Botao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao6MouseClicked
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_Botao6MouseClicked

    private void Botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao1MouseClicked
       jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_Botao1MouseClicked

    private void Botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao2MouseClicked
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_Botao2MouseClicked

    private void Botao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao3MouseClicked
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_Botao3MouseClicked

    private void BotaoBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBackspaceMouseClicked
        if(jTextField1.getText().length() > 0){
            if(jTextField1.getText().charAt(0) == '=' || "Operação inválida!".equals(jTextField1.getText())){
                jTextField1.setText("");
            }
            else{
                jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length() - 1));
            }
        }
    }//GEN-LAST:event_BotaoBackspaceMouseClicked

    private void BotaoIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoIgualMouseClicked
//        try{
//            String texto = jTextField1.getText();
//            if(jTextField1.getText().charAt(0) == '='){
//                texto = jTextField1.getText().substring(2, jTextField1.getText().length());
//            }
//            
//            ScriptEngineManager mgr = new ScriptEngineManager();
//            ScriptEngine engine = mgr.getEngineByName("JavaScript");
//            jTextField1.setText("= " + engine.eval(texto));
//        }
//        catch(Exception ex){
//            jTextField1.setText("Operação inválida!");
//        }
    }//GEN-LAST:event_BotaoIgualMouseClicked

    private void BotaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimparMouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_BotaoLimparMouseClicked

    private void BotaoAdicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAdicaoMouseClicked
        jTextField1.setText(jTextField1.getText() + "+");
    }//GEN-LAST:event_BotaoAdicaoMouseClicked

    private void BotaoSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSubtracaoMouseClicked
        jTextField1.setText(jTextField1.getText() + "-");
    }//GEN-LAST:event_BotaoSubtracaoMouseClicked

    private void Botao0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao0MouseClicked
         jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_Botao0MouseClicked

    private void BotaoMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMultiplicacaoMouseClicked
        jTextField1.setText(jTextField1.getText() + "*");
    }//GEN-LAST:event_BotaoMultiplicacaoMouseClicked

    private void BotaoDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoDivisaoMouseClicked
        jTextField1.setText(jTextField1.getText() + "/");
    }//GEN-LAST:event_BotaoDivisaoMouseClicked

    private void Botao1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Botao1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao1KeyPressed

    private void BotaoVirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVirgulaMouseClicked
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_BotaoVirgulaMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       if (evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){
            BotaoIgual.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void BotaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIgualActionPerformed
        try{
            String texto = jTextField1.getText();
            if(jTextField1.getText().charAt(0) == '='){
                texto = jTextField1.getText().substring(2, jTextField1.getText().length());
            }
            
            ScriptEngineManager mgr = new ScriptEngineManager();
            ScriptEngine engine = mgr.getEngineByName("JavaScript");
            jTextField1.setText("= " + engine.eval(texto));
        }
        catch(ScriptException ex){
            jTextField1.setText("Operação inválida!");
        }
    }//GEN-LAST:event_BotaoIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao0;
    private javax.swing.JButton Botao1;
    private javax.swing.JButton Botao2;
    private javax.swing.JButton Botao3;
    private javax.swing.JButton Botao4;
    private javax.swing.JButton Botao5;
    private javax.swing.JButton Botao6;
    private javax.swing.JButton Botao7;
    private javax.swing.JButton Botao8;
    private javax.swing.JButton Botao9;
    private javax.swing.JButton BotaoAdicao;
    private javax.swing.JButton BotaoBackspace;
    private javax.swing.JButton BotaoDivisao;
    private javax.swing.JButton BotaoIgual;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoMultiplicacao;
    private javax.swing.JButton BotaoSubtracao;
    private javax.swing.JButton BotaoVirgula;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
